### PR TITLE
[BACKLOG-35397] - Fix integration tests for cpf project to run in both Java 11 and Java 8

### PR DESCRIPTION
**Pull request by bcostahitachivantara**
@smmribeiro 
@andreramos89 
@renato-s 

@ricksjames

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 2m 53s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
:ok_hand: All tests passed!
 
Tests run: **72**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/cpf-plugin/job/PR-167/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by peterrinehart — APPROVED** [review]

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 2m 10s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
:ok_hand: All tests passed!
 
Tests run: **72**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/cpf-plugin/job/PR-167/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 2m 18s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
:ok_hand: All tests passed!
 
Tests run: **72**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.pentaho.net/job/projects/job/cpf-plugin/job/PR-167/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by smmribeiro — APPROVED** [review]
Looks good!

**Pull request merged**
